# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='school',
            field=models.CharField(default='Default School', max_length=200),
            preserve_default=False,
        ),
    ]
