# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 04:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_team_school'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contestant',
            unique_together=set([('first_name', 'last_name', 'team')]),
        ),
    ]
