# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ('first_name',)},
        ),
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254, verbose_name='Preferred email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='profile_image',
            field=models.ImageField(upload_to='members/profiles/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='website',
            field=models.CharField(blank=True, max_length=200, verbose_name='Website URL'),
        ),
    ]
